#docker build . -t rdsnb  -f Dockerfile.RDSNB
#docker run -v ${PWD}:/home/jovyan/work -p 8887:8888 rdsnb
FROM jupyter/datascience-notebook:r-4.1.2
USER root
RUN cd /root/ && wget http://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2 && tar -xvf parallel-latest.tar.bz2 && cd `ls -1t|grep -Pi 'para'|tail --lines=1` && ./configure && make && make install
USER jovyan
RUN Rscript -e 'install.packages("tictoc", repos="https://cloud.r-project.org")'
RUN Rscript -e 'install.packages("forecast", repos="https://cloud.r-project.org")'
RUN Rscript -e 'install.packages("doParallel", repos="https://cloud.r-project.org")'
